"""Add Customer model

Revision ID: 901effa4716e
Revises: 2258c3c9a3d8
Create Date: 2024-12-31 21:06:49.886636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901effa4716e'
down_revision = '2258c3c9a3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('metronome_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metronome_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
